### ISSUE TITLE
Controlling

### ISSUE THREAD

**Issue by JamesKennewell** [gravypower/node-red-contrib-melview#1]
Been trying to figure out how to control my aircon, this is exactly what im after.

Just trying to figure out controlling, what format can i use for input to set temp, on/off status, zones/rooms, mode etc?

**Comment by gravypower** [comment]
Hey @JamesKennewell this is still a work in progress so things may not be fully complete and may change. I will update the read me soon with more details of what you are after. The quick version:
You install this node 

1. Add the unitcommand node to your flow
2. Open the configuration 
3. Add an new configuration node 
4. Save
5. Deploy, you need to deploy now as the configuration node makes a call to melview to get the rooms in your house so you can finish the configuration of the unitcommand node. (I am not happy with this process but its the only way I could get things working)
6. Open the the configuration again.
7. Select the room and fill out the form.

You just need to trigger the node currently for it to send the command to melview.  I have not set up passing it values via the payload yet but this is to come.  If you have a newer wifi control module this may not be the best way to control your heat pumps. Anything later than MAC-558IF-E you can sent local commands to, best case is MAC-568IF-E. I plan to support more wifi modules in the future when I can get my hands on some.

**Comment by gravypower** [comment]
Closing issue, if you have any further questions @JamesKennewell please reopen.
